import uv

type
  UVErrorCode* = distinct cint
  UVError* = object of CatchableError
    errorCode*: UVErrorCode

proc `$`*(err: UVErrorCode): string {.inline.} =
  $uv_strerror(err.cint)

proc createUVError*(err: UVErrorCode): ref UVError =
  (ref UVError)(errorCode: err, msg: $err)

proc raiseUVError*(err: UVErrorCode) =
  raise (ref UVError)(errorCode: err, msg: $err)

template importError(name): untyped =
  let name* = UVErrorCode(uv.name)

# error
importError(UV_E2BIG)
importError(UV_EACCES)
importError(UV_EADDRINUSE)
importError(UV_EADDRNOTAVAIL)
importError(UV_EAFNOSUPPORT)
importError(UV_EAGAIN)
importError(UV_EAI_ADDRFAMILY)
importError(UV_EAI_AGAIN)
importError(UV_EAI_BADFLAGS)
importError(UV_EAI_BADHINTS)
importError(UV_EAI_CANCELED)
importError(UV_EAI_FAIL)
importError(UV_EAI_FAMILY)
importError(UV_EAI_MEMORY)
importError(UV_EAI_NODATA)
importError(UV_EAI_NONAME)
importError(UV_EAI_OVERFLOW)
importError(UV_EAI_PROTOCOL)
importError(UV_EAI_SERVICE)
importError(UV_EAI_SOCKTYPE)
importError(UV_EALREADY)
importError(UV_EBADF)
importError(UV_EBUSY)
importError(UV_ECANCELED)
importError(UV_ECHARSET)
importError(UV_ECONNABORTED)
importError(UV_ECONNREFUSED)
importError(UV_ECONNRESET)
importError(UV_EDESTADDRREQ)
importError(UV_EEXIST)
importError(UV_EFAULT)
importError(UV_EFBIG)
importError(UV_EHOSTUNREACH)
importError(UV_EINTR)
importError(UV_EINVAL)
importError(UV_EIO)
importError(UV_EISCONN)
importError(UV_EISDIR)
importError(UV_ELOOP)
importError(UV_EMFILE)
importError(UV_EMSGSIZE)
importError(UV_ENAMETOOLONG)
importError(UV_ENETDOWN)
importError(UV_ENETUNREACH)
importError(UV_ENFILE)
importError(UV_ENOBUFS)
importError(UV_ENODEV)
importError(UV_ENOENT)
importError(UV_ENOMEM)
importError(UV_ENONET)
importError(UV_ENOPROTOOPT)
importError(UV_ENOSPC)
importError(UV_ENOSYS)
importError(UV_ENOTCONN)
importError(UV_ENOTDIR)
importError(UV_ENOTEMPTY)
importError(UV_ENOTSOCK)
importError(UV_ENOTSUP)
importError(UV_EOVERFLOW)
importError(UV_EPERM)
importError(UV_EPIPE)
importError(UV_EPROTO)
importError(UV_EPROTONOSUPPORT)
importError(UV_EPROTOTYPE)
importError(UV_ERANGE)
importError(UV_EROFS)
importError(UV_ESHUTDOWN)
importError(UV_ESPIPE)
importError(UV_ESRCH)
importError(UV_ETIMEDOUT)
importError(UV_ETXTBSY)
importError(UV_EXDEV)
importError(UV_UNKNOWN)
importError(UV_EOF)
importError(UV_ENXIO)
importError(UV_EMLINK)
importError(UV_EHOSTDOWN)
importError(UV_EREMOTEIO)
importError(UV_ENOTTY)
importError(UV_EFTYPE)
importError(UV_EILSEQ)
importError(UV_ESOCKTNOSUPPORT)
importError(UV_ENODATA)
importError(UV_EUNATCH)
